# Copyright (C) 2018-2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/universal7904-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    $(LOCAL_PATH)
    

PRODUCT_COPY_FILES += \
    proprietary/lib/hw/audio.playback_record.default.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/audio.playback_record.default.so \
    proprietary/lib/libHMT.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libHMT.so \
    proprietary/lib/lib_SoundAlive_3DPosition_ver202.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_SoundAlive_3DPosition_ver202.so \
    proprietary/lib/lib_SoundAlive_AlbumArt_ver105.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_SoundAlive_AlbumArt_ver105.so \
    proprietary/lib/lib_SoundAlive_play_plus_ver210.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_SoundAlive_play_plus_ver210.so \
    proprietary/lib/lib_SoundBooster_ver950.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_SoundBooster_ver950.so \
    proprietary/system_ext/apex/com.android.vndk.v29/lib/libcamera_client.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/apex/com.android.vndk.v29/lib/libcamera_client.so \
    proprietary/lib/libprofileparamstorage.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libprofileparamstorage.so \
    proprietary/lib/libsecaudiocoreutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsecaudiocoreutils.so \
    proprietary/lib64/hw/audio.playback_record.default.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/audio.playback_record.default.so \
    proprietary/lib64/libHMT.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libHMT.so \
    proprietary/lib64/lib_SoundAlive_3DPosition_ver202.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/lib_SoundAlive_3DPosition_ver202.so \
    proprietary/lib64/lib_SoundAlive_AlbumArt_ver105.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/lib_SoundAlive_AlbumArt_ver105.so \
    proprietary/lib64/lib_SoundAlive_play_plus_ver210.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/lib_SoundAlive_play_plus_ver210.so \
    proprietary/lib64/lib_SoundBooster_ver950.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/lib_SoundBooster_ver950.so \
    proprietary/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptX_encoder.so \
    proprietary/lib64/libprofileparamstorage.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libprofileparamstorage.so \
    proprietary/lib64/libsecaudiocoreutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsecaudiocoreutils.so
